[package]
name = "generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive", "std", "help", "color", "usage"], default-features = false }
oxc_allocator = "0.11.0"
oxc_ast = "0.11.0"
oxc_parser = "0.11.0"
oxc_span = "0.11.0"
reqwest = { version = "0.12.10", features = ["blocking"] }
parking_lot = "0.12.1"
proc-macro2 = "1.0.79"
quote = "1.0.35"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
syn = "2.0.57"
